"""init

Revision ID: 14e8a900292f
Revises: cce7f49dee5d
Create Date: 2021-03-12 17:28:51.462212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e8a900292f'
down_revision = 'cce7f49dee5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_instances', schema=None) as batch_op:
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
