"""connections-name-unique

Revision ID: 44bf8bf6d943
Revises: bca52b3ecbd0
Create Date: 2021-02-14 19:50:10.048737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bf8bf6d943'
down_revision = 'bca52b3ecbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
