"""init

Revision ID: 73de78c56c89
Revises: 14e8a900292f
Create Date: 2021-03-18 17:11:25.016466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73de78c56c89'
down_revision = '14e8a900292f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
