"""init

Revision ID: 9cb3078019ff
Revises: a4cabf49f4cd
Create Date: 2021-04-09 17:44:55.511153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb3078019ff'
down_revision = 'a4cabf49f4cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('database', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vendor', sa.String(length=50), nullable=True))
        batch_op.drop_column('service')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('vendor')
        batch_op.drop_column('database')

    # ### end Alembic commands ###
