"""init

Revision ID: a4cabf49f4cd
Revises: 6aff78fc39d4
Create Date: 2021-04-02 15:40:36.482530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4cabf49f4cd'
down_revision = '6aff78fc39d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
