"""init

Revision ID: bb821841a523
Revises: f72cc43ac2d9
Create Date: 2021-03-07 00:04:20.347707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb821841a523'
down_revision = 'f72cc43ac2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('worker_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('worker_count')
        batch_op.drop_column('sample_size')

    # ### end Alembic commands ###
