"""init

Revision ID: c2d881d6a43e
Revises: bb821841a523
Create Date: 2021-03-07 19:51:50.355725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d881d6a43e'
down_revision = 'bb821841a523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
