"""init

Revision ID: f6dd2079ec2d
Revises: cac54f56e868
Create Date: 2021-04-13 12:08:54.449224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6dd2079ec2d'
down_revision = 'cac54f56e868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
